### ISSUE TITLE
Add doc to explain what to do if one forgot to do a mob next

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#111]
See thread https://twitter.com/MarioKusek/status/1352862638808686594?s=20

**Comment by MarioKusek** [comment]
You asked here: https://twitter.com/simonharrer/status/1352994206931951617 How did you recover?

Here follows answer to my students (this may be overcomplicated but I tried to cover all cases).

**We did not save the files before switching to the new driver**

If we did not save the files, and we started `mob next`, the content of the changed files remains in the editor and is not transferred to the remote git repository, so other drivers cannot download it.

The main problem is if the editor monitors the changes on the disk and notices that a change has occurred and reloads the file from the disk. In that case, what we had in the editor is lost.

**The next driver has done nothing yet**

The solution is as follows:

1. restart the session with `mob start`
2. if the editor asks to load something from the disk you should be refused to load it
3. save the file
4. switch the session to the next driver by running `mob next`

**The other driver had already downloaded the code, but had not changed anything**

Other driver need to do following:

1. if he/she has already execute a `mob start` then he/she should switch the session so that he/she starts `mob next`. If he/she did not execute `mob start` this step should be skipped.

First driver need to do following:

1. restart the session with `mob start`,
2. if the editor asks to load something from the disk it should be refused to load it
3. save the file
4. switch the session to the next driver by running `mob next`

After that next driver can take session with `mob start`.

**Next driver has already downloaded the code, started the session and changed the file**

In this case we have two options:

1. if we do not want to keep the change of another driver
  a. second driver: return the original version of the file by executing `git checkout filename`
  b. second driver: move the session with `mob next`
  c. first driver: take over the session with `mob start`
  d. first driver: save file
  e. first driver: switch session with `mob next`
  f. second driver: take over the session with `mob start`
2. if we want to keep the change of another driver
  a. other driver: save file
  b. other driver: execute `mob next`
  c. first driver: save file
  d. first driver: save this version of the file with `git stash`
  e. first driver: take over the session with `mob start`
  f. first driver: merge files with `git stash pop`
  g. first driver: open all files that have conflicts and fix them manually
  h. first driver: add all files to the index with `git add .`
  i. first driver: switch session with `mob next`
  j. second driver: take over the session with `mob start`

**Comment by simonharrer** [comment]
Added a best practice to enable autosave https://github.com/remotemobprogramming/mob/blob/main/README.md#best-practices as this would have prevented those situations.

Otherwise, I'm not sure how to proceed from there. These steps are pretty long so I don't want them in the README in that form. Also, it's really an edge case when one doesn't have autosave on. Any ideas where this or a subset of it could be put?

**Comment by simonharrer** [comment]
I'm closing this now due to inactivity. If there's an urge to reopen, feel free to do so.
