### ISSUE TITLE
Add env variable to always enable a timer with a specific value

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#141]
Enable with
MOB_TIMER=4

Disable with empty value.

**Comment by janmax** [comment]
I'll give it a try! A few questions: 
* What should happen if `MOB_TIMER=X` is set but someone starts a new session with `mob start Y`? I would suggest Y takes precedence.
* Should the unit be configurable? If so, I'd suggest defaulting to minutes if no unit is given, otherwise use a format that works with [ParseDuration](https://golang.org/pkg/time/#ParseDuration).

**Comment by simonharrer** [comment]
Yes mob start 4 should override the value set via an env variable. 

Let’s start with an integer for minutes. Not sure if a duration here is really that helpful.
