### ISSUE TITLE
Did we intend to deprecate older Go versions and rename the executable to `mob.sh`?

### ISSUE THREAD

**Issue by stevegt** [remotemobprogramming/mob#151]
While touch-testing #121 today it took me several confusing minutes to figure out why none of the new features were showing up in `mob`, and after a lot of thrashing around I finally realized my `mob` executable wasn't rebuilding when I ran `go build`.  I finally found this in go.mod, last modified in 878661c5:

```
module mob.sh

go 1.16
```

That causes `go build` to build an executable named `mob.sh`, which will cause these issues:

- an `.sh` suffix implies a shell script -- my eyes didn't spot it as a Go executable
- the name change from `mob` to `mob.sh` breaks a buncha local code that assumes the executable is named `mob`
- the new name disagrees with examples in the README

The upgrade from version 1.15 to 1.16 is also puzzling me -- the code builds and the tests pass in our org's 1.14.2 environment, though I admit I may be missing something, and I didn't try this in a fresh Go 1.14.2 install with an empty local package cache 'cause I'm busy today digging into #121.  Did we bump that version number because of requirements that need 1.16 features?

**Comment by stevegt** [comment]
The more I stare at this, the more I think it must be something that works on macos with brew, but it sure doesn't work with a vanilla `go build` on Linux.  I'd provide a simple PR to revert it, but am not sure if that's going to break something for @Morl99, and don't want to cause ping-ponging reverts.  Carsten, do you have access to a Linux box, maybe in a container or VM somewhere?

**Comment by Morl99** [comment]
Hello @stevegt,

I am sorry, that this causes trouble for you. Bumping to 1.16 was intentional (see the Readme), although I don't know if it is mandatory. I am no Go wizard, and don't really understand how the module system works, I googled my way through it. We needed the module file to make the project compatible with Go 1.16.

I also get, that the binary name is confusing, would it be enough to rename the module to "mob"? Unfortunately the go binary names that are generated by the module system are rather ugly. Do you know a way around this without renaming the module?

I can test this in a Linux docker for sure, but the Pipeline also runs on Ubuntu and it works there. Can you test this in a clean 1.16 environment yourself and see if any issues persist?

**Comment by simonharrer** [comment]
I like to keep up to the latest golang releases. That’s why we are at go 1.16.

Since 1.16 go enforced to have a module.

Modules in go typically are based on a domain.

During the CI pipeline the binary is named either mob or mob.exe via the -o parameter. See release.yaml. 

In the install script we use go build mob.go to create the binary with the correct name. If you have an idea how to change the binary name of go build that’s great. But I wouldn’t want to switch back to older versions of golang.

**Comment by stevegt** [comment]
**Module directive**

The `module` directive controls the name of the binary.  To build a `mob` binary, set the module name to `mob` or mob.sh/mob`.  The binary name is based on the last path component.  

The domain name can be included in the `module` directive but is not required in all cases, and in the case of a project hosted at github, the module path should start with `github.com`.  In the case of the `mob` tool, the module path should be `https://github.com/remotemobprogramming/mob`.

Requiring the `-o` flag when building is unnecessary given the above.

**Go version:**

The 1.16 version of Go does not enforce modules -- it only defaults GO111MODULE=on, which means that by default you need a go.mod file.

While 1.16 wants modules, the reverse is not true -- the use of a go.mod file does not require upgrading to 1.16.  Modules have been supported since 1.11.

There are no 1.16 language features required for building `mob` -- we're running on 1.14.2, for instance.  

Specifying 1.16 as the language version in go.mod does not prevent building with older language versions -- it only tells the compiler what language features to turn on and off.  As far as I can tell, there  are no 1.16 language versions required for building `mob`.

Specifying 1.16 as the language version in go.mod does lead users to believe they can't use the tool without first upgrading their environment.  In larger organizations, this upgrade can involve a lot of people and have a long lead time.

Best practice would be to bump the language version in go.mod only when you discover a new language feature you must have -- otherwise leave it at the lowest known-working version.

**Comment by stevegt** [comment]
Fixed a bunch of bad typos in my last message, so if you're following this in email, check https://github.com/remotemobprogramming/mob/issues/151#issuecomment-804315147 -- that should make more sense.

**Comment by Morl99** [comment]
Thanks @stevegt, that all makes a lot of sense, and I am beginning to get a better grasp of how go is intended to work with packages.

I tested it on my local machine, and, apart from the things that you mentioned, this also fixes the ability to run the tests with IntelliJ (even single ones), since IntelliJ now correctly identifies the package. That was somehow broken before and you needed to switch the test kind to `directory`. 

I see two more things in your PR, that could be improved:
The "How to contribute" section still mentions go 1.16 as a minimum.
The section about "Run the Tests from your IDE (GoLand or IntelliJ IDEA)" is obsolete now, this just works out of the box and does not need any explanation.

From a first glance, I do not believe, that the github actions need any changes. I would specifically leave the `go build -o` logic untouched, since it also handles the binary name for windows binaries, and as long as it works, I do not really see a need to modify it at this point.

**Comment by stevegt** [comment]
@Morl99 I just now tried `GOARCH=amd64 GOOS=windows go build` on my linux machine -- it built mob.exe as expected, so I believe even the -o logic for windows is redundant.  That probably should be redacted so it doesn't confuse someone in the future, but I agree that should wait until the next time someone updates release.yaml.
