### ISSUE TITLE
Configure branch-separators

### ISSUE THREAD

**Issue by MrGung** [remotemobprogramming/mob#165]
While mob-programming we sometimes git-push the current source, triggering an CI-build. Due to the format of the mob-branch's name, the build fails. The pipeline cannot handle the name of the branch: `mob/develop`.

I'd like to be able to configure the separator, e.g. to get something like `mob-develop`.

Or - if there are other suggestions...

**Comment by simonharrer** [comment]
That's a tough one. The `mob/` prefix is currently hard coded because it's part of the contract between everybody using that tool. Changing that would require everybody using that specific repo to use another (but the same) prefix. And a lot of functionality is based on that prefix. Changing that isn't that easy.

One solution would be if the prefix is configured in a file `.mob` within the repository. Then, it is guaranteed that everybody uses the same prefix. But not sure if this is what would really be accepted.

I'm wondering why the CI build cannot handle such branch names? Which CI Pipeline do you use?

**Comment by MrGung** [comment]
Since we are already using some of the environment-variables to tackle project/team-wide settings, I thought it would be a viable way to also include the branch-separator as a variable.

In our Jenkins-pipeline we publish into Artifactory - the artifact's name includes the name of the branch (and that breaks). I could - and will - change that to replace the / - but I wouldn't like to have to do it in every project we'd like to use mob in.

**Comment by simonharrer** [comment]
Hm, we could add it as experimental and see whether we keep that environment variable. How does that sound?

**Comment by simonharrer** [comment]
Did implement this for 1.5.0 as experimental. We'll see whether it'll make it out of an experimental state.
