### ISSUE TITLE
Add wipBranch as a parameter of start

### ISSUE THREAD

**Issue by talesbaz** [remotemobprogramming/mob#27]
As the most part of parameters, except `timer` and `wip-branch`, doesn't change between developing cycles. What you think if the start function receives a second parameter "wip-branch"  and in that sense avoiding the need to export the variable to the env. 
I can perform the change, just need a "good to go" signal. 

In time, Thx for the tool!

**Comment by simonharrer** [comment]
Feature makes sense. At the moment, there's the following format:

`mob start [MINUTES [SHARE_FLAG]]` with three possible invocation scenarios:

```
mob start
mob start 10
mob start 10 share
```

Not sure how your option should add to that. Any ideas on how to handle that?

You work with multiple wip-branches at the same time? Would be interested on why you do that. Because we (my team) don't. Forces us to stay true to our wip limit.

**Comment by talesbaz** [comment]
I think we can parameterize the variable because its an env var, like: ```mob start 10 share --wip-branch=feature``` 
My team work with just one wip-branch too but what were I aiming here is to avoid the need to export this env var.

**Comment by simonharrer** [comment]
ok, sounds good. You can have a go at this. Looking forward to your review.

**Comment by simonharrer** [comment]
Closed issue due to inactivity. Please reopen if you plan to work on it @talesbaz
