### ISSUE TITLE
Remove 'mob reset' command

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#36]
I'm thinking of removing the 'mob reset' command as I've only used it like 4 times in 2 years. Not sure, it's that helpful.

**Comment by jlangr** [comment]
I have not used it...

However:
- I've been setting MOB_STAY to true. It's sometimes useful to browse the same file that the driver is looking at. Maybe I should stop doing that, though.
- When I start a new mob session at a later time, it turns out the best thing to do is blow away the mob session branch because it's out of sync with origin... I haven't thought about "why" much, i.e. exactly how it gets in that state. So mob reset might be useful here, but I think knowing that is part of the problem.

There is something to be said for abstracting away git almost entirely... so I'd almost prefer to see it kept around; it also handles blowing away both local & origin, so that's a small plus.

I guess the big sin is for someone know when they should forcefully blow away mob-session.

**Comment by simonharrer** [comment]
Keeping it for now.
