### ISSUE TITLE
allow mob next with message commit to still have the CI skip flag

### ISSUE THREAD

**Issue by kamalhm** [remotemobprogramming/mob#433]
when using mob next with `-m` flag for adding commit message, i was surprised to see that it triggers my build pipeline because it doesnt have the usual CI skip commit message. Can we add the commit message and still keep the skip CI commit text in the commit message?

**Comment by hollesse** [comment]
You could just add the ci skip in your new message. But I think it wouldn't be a good idea to change the acutal behavior. If you choose to create a custom message it is mostly because you finished something that is a step which is somehow completed and therefore should be build.

Why would you expect that the ci should not run on this commit?

**Comment by hollesse** [comment]
due to lack of feedback I close this issue
