### ISSUE TITLE
Multiple WIP branches per base branch

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#44]
The default way of working with 'mob' is using one WIP branch per base branch. Because of backwards compatibility, "master" and "mob-session" are special. 

```
# base branch is 'master'
master $ mob start
mob-session $ mob done # return to 'master'

# base branch is 'feature1'
feature1 $ mob start
mob/feature1 $ mob done # return to 'feature1'
```

Multiple WIP branches per base branch is currently not possible anymore, as the config parameter for the base branch and the WIP branch have been removed.

The need for multiple wip branches per base branch is, however, there (see https://github.com/remotemobprogramming/mob/issues/15 and https://github.com/remotemobprogramming/mob/issues/27).

My suggestion would be as follows:

```bash
# base branch is 'master'
master $ mob start --branch green
mob/master/green $ mob done # return to 'master'

# base branch is 'feature1'
feature1 $ mob start -b green
mob/feature1/green $ mob done # return to 'feature1'
```

Because the base branch is encoded into the wip branch name, 'mob' knows the base branch when on the WIP branch without any additional files polluting any commits.

With MOB_NEXT_STAY=true, the subsequent 'mob start' calls wouldn't need the '--branch green' info, as one would already be on the wip branch named 'green'.

```
# base branch is 'master'
master $ mob start --branch green
mob/master/green $ MOB_NEXT_STAY=true mob next
mob/master/green $ mob start
mob/master/green $ mob done # return to 'master'
```

The `mob reset` command would need the `--branch` parameter as well, so that WIP branch can be nuked, too. 

Would love your feedback @jlangr @OskarD @talesbaz

**Comment by talesbaz** [comment]
Hey @simonharrer, first things first, sorry for not implement my suggestion. 
Analyzing your suggestion this approach will do the trick, at least for me and my team.

**Comment by jlangr** [comment]
There's a concern that if I forget to specify the branch name, it will go to mob-session and I might not notice before I start making a mess.

You could fix that, I suppose, by seeing what WIP branches exist and if more than one for a given base branch, insist that the --name parameter be provided.

**Comment by simonharrer** [comment]
Hey @talesbaz thanks for the feedback. And no worries! I'm already very thankful for your comments. 

@jlangr I do like that safeguard. Great idea.

So in summary, I think this might be a way to move forward.

**Comment by schuchert** [comment]
So we are using 0.0.18 and it appears to support multiple committers off of master.

When I tried to upgrade via brew, it installed 0.0.20 (and I lost 0.0.18 from the cellar). This version does not allow two committers off of master.

If we have to create feature branches, then there's no point to using this tool as I'm doing manually as much work as this tool saves.

So for now we are going to stick with 0.0.18. (And as far as I've been able to tell, that's a manual hack as I'm not smart enough to get home brew to help with that, my google skills have failed me.)

Will the ability to have multiple committers on the master return? It's a deal breaker for us to have to create feature branches to do quick hand-off.

**Comment by simonharrer** [comment]
@schuchert the proposal discussed in this issue here should fulfill your need to having multiple WIP branches off of master. I plan to implement this issue this week. Does this suffice?

**Comment by schuchert** [comment]
@simonharrer yes. and by the way, I can confirm (from working with several mobs) that everybody using it (12 people) LOVE it. The lag we've had from screen sharing with webex or TeamViewer has made remote mobbing painful.

So 
 * thank you for creating this tool (0.0.18 is working fine for all of us).
 * I've been promoting it (as have a few others) so you're likely to get 50+ users from our consulting gig (that's likely an under estimate).
 * Your tool has profoundly changed my thinking on the imporatnce of having consistent environments when pairing/mobbing in a team setting. 

I am able to take keyboard and keep the vi plugin turned on, and nobody has to suffer my vi habbit. 

This "simple" tool has huge positive ramifications in actual daily use. And given that where I'm working, we are not going back to the office before September (next year for me as I travel), we'll keep using it.

I plan to recommend we use it even when we can sit at a mobbing station. Rather than switching who is sharing, each person will plug in their laptop to a shared screen. The slight hassle of switching who's plugged into to a shared monitor is well worth having my own enviornment.

**Comment by simonharrer** [comment]
Implemented in https://github.com/remotemobprogramming/mob/commit/8adf25da61938b55d5f15f6a8abc4e4d413c33c6
