### ISSUE TITLE
Proposing a config file approach

### ISSUE THREAD

**Issue by Richsan** [remotemobprogramming/mob#45]
Hello folks, first thanks for the creation of this excellent tool, I'm using with my teammates in the company that I work, it's helping us a lot in this period of remote work.
To adapt the tool to some of our needs and daily uses, I've made a fork to implement some ideas and changes, and I would like to present this ideias as suggestions of features , most of them I've already implement in the fork but there's yet some minor adjustments to be made and test in windows.
So here goes the suggestions:

- **Change the variable environment config approach to a file config approach:**
The configuration of mob tool is managed by environment variables, this approach  imply in the necessity of make some setup in machines and keeps it synchronized with the  configurations of the session's participants, this make the usability of the tool for us harder and complicated.
So my suggestion is to use a json config file, which in my implementation I've called `.mob_config.json `, this file would be created with defaults config parameters when the `mob start` command was called for the first time and there's no config file present, this config file will be pushed for the entire mob session until the command `mob done` was called, in this moment the tool will delete the config file on the squash with the base branch.

- **A `mob setup` command:**
A command to define all configuration, one by one, of the mob session instead to use the defaults configuration of the mob start command.

- **The base default branch be the current branch:**
Instead use the master as default base branch use the current branch as default base branch.

- **The wip default branch be a branch where the name is a composition of the base branch with a suffix.**
In our implementation we've used the suffix `-wip`, so if the base branch was called, for example, "feature" , the default wip branch is "feature-wip".

- **A License file.**
I've noticed later that the project doesn't have a License file or written in the README file explicit, would be nice to define one license to the project and turn this explicit.

My fork (it's still a WIP, I need fix some errors and update the README file with the new commands and test with windows):
https://github.com/Richsan/mob

**Comment by Richsan** [comment]
The fork was made with an old version of the project, so some new commits it's not present in the fork

**Comment by simonharrer** [comment]
Hi @Richsan thanks for your feedback and care about the 'mob' tool. 

I already followed your suggestion and added a license (see #47).

Your wish for "The base default branch be the current branch" is already granted, and included in the latest and greatest 'mob' tool. To know the base branch name, it's encoded into the WIP branch name as follows: "mob/feature1". So the tool always knows from which base branch the wip branch was created and can determine the base branch for a 'mob done' easily.

Regarding "The wip default branch be a branch where the name is a composition of the base branch with a suffix." this is currently discussed as part of #44. Feel free to have a look at that issue.

But to your general point: I had a tool in mind without the need of environment variables for configuration. And I think we might get there.

1. The MOB_NEXT_STAY option will become the new "default" in the future (and the config option will be removed then). 
2. The option MOB_WIP_COMMIT_MESSAGE is not that important, I think. Or, in other words, I think this can be removed as well. 
3. The option MOB_START_INCLUDE_UNCOMMITTED_CHANGES should be removed as well, because there's a parameter at mob start that handles that. 
4. Only on linux is the need to configure MOB_VOICE_COMMAND because on macOS this variable already works fine and on windows that variable is ignored as a better alternative is used.
5. MOB_REMOTE_NAME is not something that really should be configured.

That's why I don't think a configuration by the user is really necessary.

**Comment by Richsan** [comment]
Ohh sorry @simonharrer , I've not noticed the last updates since I forked the project.
Yeah, in this way using current branch as default and with the pattern implemented for WIP branch remove in a great and nice way the need of most of configs and makes sense not use a config file.
