### ISSUE TITLE
'mob start' commit opt-in?

### ISSUE THREAD

**Issue by mightyiam** [remotemobprogramming/mob#461]
Hey, since v5, there's no 'mob start' commit. For [git-trim](https://github.com/foriequal0/git-trim), a 'mob start' commit is helpful. Is this feature opt-in now, or is it gone?

Sorry for being a [spacebar heater](https://xkcd.com/1172/).

**Comment by hollesse** [comment]
It is gone as we saw more problems with the mob start commit as it helped. It was introduced to avoid running the ci when mob start is done even if your git remote system does not support push options. One thing that was bad about the empty commit was that if you have multiple repositories you are working on and you think you need to change something there doing mob start and then changing nothing leads to a new mob branch. If you come back later do a mob start and meanwhile have some other commits on your main branch, for example translations or dependency update which are created automatically by other systems or you just did something on main without using mob because this feature was small and then do a mob start you are on the mob branch created weeks ago. This lead to a lot of problem for some people including my own team. As the benefit from this mob start commit was very low but the also the complexity of the mob tool got increased heavily by this change we decided to remove this feature again. 

I hope this helps to understand why we have done this.

**Comment by hollesse** [comment]
@mightyiam could you please explain me how the mob start commit helped with git trim and what you where trying to archive? Would love to understand the Problem it solved for you.

**Comment by mightyiam** [comment]
I appreciate your willingness to understand my use case, @hollesse.

I find git-trim useful in its intended purpose; to easily remove branches that are of no value.

Local branches that are not ahead of their remote tracked branch them are by default subject to removal. So back when `mob start` was adding an empty commit, git-trim did not remove the `foo` counterpart of `mob/foo`. Now that `foo` is not ahead, git-trim by default removes it. It's a false positive.

I'm not sure how to prevent that short of forking.

**Comment by hollesse** [comment]
If you use git trim mostly for mob branches you could just use mob clean.

**Comment by mightyiam** [comment]
That's sound advice, but I do use it for non-mob branches, as well.
