### ISSUE TITLE
Make MOB_NEXT_STAY=true the new default

### ISSUE THREAD

**Issue by simonharrer** [remotemobprogramming/mob#54]
I plan to switch the default values. Instead of switching back to the base branch every time, the default would be to stay on the wip branch by default. The option can still be used to disable that behavior with MOB_NEXT_STAY=false.

Why? We work with Java, and if you add a new dependency in your wip branch and constantly switch back and forth, the IDE has a hard time syncing your build files. Also, syncing with file system changes is sometimes slow in some IDEs. This change would reduce that friction. Another point: sometimes one wants to look at the stuff already done during the mob session as part of the rest of the mob to contribute better to the discussion. This change would help as well, as some might not know the MOB_NEXT_STAY option and then would have to execute 'mob start' locally. 

Would love to discuss how you feel about this.

**Comment by Morl99** [comment]
In the beginning, I felt the way you feel now. But at some point I thought I understood, why you had chosen to implement it the way it is now: The current behaviour does a good job in avoiding concurrent edits. It is always clear, who is the driver (the person with the branch checked out). That said, your arguments make a lot of sense as well, and it is at least partly true for node.js projects as well, because the IDE might start a reindex after switching the branch (mostly if stuff in the package.json changes). 
I think I would mostly be concerned, that this could be a confusing change, so maybe we can find a way to introduce it without surprising too many people (see other issues). How about including a warning first for people who do not alter MOB_NEXT_STAY, that the current default behavior will change in a future release, and that they should set it to =false now to make sure, that this does not surprise them?

**Comment by simonharrer** [comment]
I already added a 'deprecated' function for the environment variables `MOB_DEBUG` and `MOB_START_INCLUDE_UNCOMMITTED_CHANGES`. I agree, something similar for `MOB_NEXT_STAY` would make sense.

**Comment by simonharrer** [comment]
I just added the following so support a smooth transition.

> Adds flag `--return-to-base-branch` (with shorthand `-r`) to return to base branch on `mob next`. Because 'mob' will change the default behavior from returning to the base branch to staying on the wip branch on `mob next`, this flag provides the inverse operation of `--stay`. If both are provided, the latter one wins.

**Comment by simonharrer** [comment]
The `--return-to-base-branch` option is part of the new release 0.0.25

Next, some kind of deprecation info should be displayed. Not sure when and how yet.

**Comment by simonharrer** [comment]
@Morl99 I now print "Attention: MOB_NEXT_STAY will default to 'true' in future versions. Set MOB_NEXT_STAY to 'false' to keep old behavior." when the user neither has MOB_NEXT_STAY set nor uses `--stay` or `--return-to-base` as parameters. It's only printed when executing `mob next` so this should not be that annoying then.

**Comment by simonharrer** [comment]
Closing this as it'll be in v1.0.0 which is planned to be released at beginning of December.
